apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # user
  - image: guyaltd/user
    context: user
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'user/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
  # Gatekeeper
  - image: guyaltd/gatekeeper
    context: gatekeeper
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'gatekeeper/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
  # Api Gateway
  - image: guyaltd/api-gateway
    context: api-gateway
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '/**/*.conf'
        dest: '.'
  # Chipmunk
  - image: guyaltd/chipmunk
    context: chipmunk
    docker:
      dockerfile: Dockerfile.dev
      target: development
      network: host
    sync:
      manual:
      - src: 'app/**/*.php'
        dest: '.'
      - src: 'public/**/*.php'
        dest: '.'
      - src: 'src/**/*.php'
        dest: '.'
      - src: 'templates/**/*.twig'
        dest: '.'
  # Mailhog Mail Server
  - image: guyaltd/mailhog
    context: mailhog
    docker:
      dockerfile: Dockerfile
  # Mocking Server
  - image: guyaltd/mocking-server 
    context: mocking-server
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: '**/*.js'
        dest: '.'
      - src: '**/*.json'
        dest: '.'
  # catalog
  - image: guyaltd/catalog
    context: catalog
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'catalog/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/gatekeeper/overlays/development
    - guya/user/overlays/development
    - guya/api-gateway/base
    - guya/chipmunk/overlays/development
    - guya/catalog/overlays/development
    - guya/mocking-server/base