apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # admin-panel
  - image: guyaltd/admin-panel 
    context: admin-panel
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: '.'
      - src: 'public/**/*.css'
        dest: '.'
      - src: 'public/**/*.js'
        dest: '.'
  # user
  - image: guyaltd/user
    context: user
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'user/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
  # Gatekeeper
  - image: guyaltd/gatekeeper
    context: gatekeeper
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'gatekeeper/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
  # Api Gateway
  - image: guyaltd/api-gateway
    context: api-gateway
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: 'api_conf.d/**/*.conf'
        dest: '.'
      - src: 'errors'
        dest: '.'
      - src: 'nginx.conf'
        dest: '.'
      - src: 'api_json_errors.conf'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/gatekeeper/overlays/development
    - guya/admin-panel/overlays/development
    - guya/user/overlays/development
    - guya/api-gateway/base