apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Api Gateway
  - image: guyaltd/api-gateway
    context: api-gateway
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '/**/*.conf'
        dest: '.'
  # admin-panel
  - image: guyaltd/admin-panel 
    context: admin-panel
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/api-gateway/base
    - guya/admin-panel/overlays/development