apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # cart
  - image: guyaltd/cart
    context: cart
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'cart/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/cart/overlays/development
