apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Chipmunk
  - image: guyaltd/chipmunk
    context: chipmunk
    docker:
      dockerfile: Dockerfile.dev
      target: development
      network: host
    sync:
      manual:
      - src: 'src/**/*.php'
        dest: '.'
      - src: 'templates/**/*.twig'
        dest: '.'
  # Mailhog Mail Server
  - image: guyaltd/mailhog
    context: mailhog
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - guya/chipmunk/overlays/development
