apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # admin-panel
  - image: guyaltd/admin-panel 
    context: admin-panel
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: '.'
      - src: 'public/**/*.css'
        dest: '.'
      - src: 'public/**/*.js'
        dest: '.'
  # Gatekeeper
  - image: guyaltd/gatekeeper
    context: gatekeeper
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'gatekeeper/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/admin-panel/overlays/development
    - guya/gatekeeper/overlays/development