apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Mailhog Mail Server
  - image: guyaltd/mailhog
    context: mailhog
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - guya/mailhog/base
