apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Mongo indexer
  - image: guyaltd/mongo-indexer
    context: mongo-indexer
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
      - src: '**/*.toml'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/mongo-indexer/base
