apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Order Service
  - image: guyaltd/order
    context: order
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'order/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/order/overlays/development