apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # payment
  - image: guyaltd/payment
    context: payment
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'payment/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/payment/overlays/development
