apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # xtrack
  - image: guyaltd/xtrack
    context: xtrack
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: '**/*.js'
        dest: '.'
  # Xtrack Simulator Server
  - image: guyaltd/xtrack-simulator
    context: xtrack-simulator
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: '**/*.js'
        dest: '.'
deploy:
  kustomize:
    paths:
    - guya/xtrack/overlays/development
