apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: guya-dev
build:
  local: 
    concurrency: 0
    push: false
  artifacts:
  # Mocking Server
  - image: guyaltd/mocking-server 
    context: mocking-server
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: '**/*.js'
        dest: '.'
      - src: '**/*.json'
        dest: '.'

  # Branch
  - image: guyaltd/branch
    context: branch
    docker:
      dockerfile: Dockerfile.dev
      target: development
    sync:
      manual:
      - src: 'branch/**/*.py'
        dest: '.'
      - src: 'tests/**/*.py'
        dest: '.'
  # Mongo Connector
  - image: guyaltd/mongo-connector
    context: mongo-connector
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - guya/mocking-server/base
    - guya/branch/overlays/development
    - guya/mongo-connector/base