apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: guya-dev
build:
  artifacts:
  - image: guyaltd/admin-panel 
    context: admin-panel
    docker:
      dockerfile: Dockerfile
      target: development
    sync:
      manual:
      - src: 'src/**/*.js'
        dest: '.'

deploy:
  kustomize:
    paths:
    - guya/admin-panel/overlays/development
